### ISSUE TITLE
how to compile kurucz stellar model

### ISSUE THREAD

**Issue by cxl4444** [RozanskiT/vidmapy#1]

**Comment by cxl4444** [comment]
I seem to find the reason that the Atlas cannot run. because I do not add the atomic_data into that directory  /vidmapy/kurucz/atomic_data/.
Emmm, because i come from china. The tar. file of atomic_data is not able to get due to the internet limit.
Would you mind send a attachment to my E-mail? this is my email address:  xinleichen@mail.ynu.edu.cn
Thanks for your kindness.

**Comment by cxl4444** [comment]
Hello,

I am a student from china.

My supervisor asks me to use the kurucz model to calculate the flux of stars. but when I compiled packages of atlas9/atlas12 etc., I failed.

Would my mind teach me the steps to compile this model's packages? 

Thank you vary much!

Best regards!

**Comment by RozanskiT** [comment]
I contacted you via email. Let's discuss installation issues there.

**Comment by cxl4444** [comment]
Hello,I am very very very glad to receive your reply.When I compile atlas12/9, there are some warning.I just compiled atlas9mem.for and atlas9v.for according to https://wwwuser.oats.inaf.it/castelli/sources/atlas9codes.html , but I failed. Than i thought maybe some file absenced, so I downloaded all the files of atlas9 from http://kurucz.harvard.edu/programs/atlas9/. It is also failed.Could you please teach me how to compile and run this program successfully?Thank you very much！！Best regards!---- Replied Message ----FromTomasz ***@***.***>Date12/17/2021 20:33 ***@***.***> ***@***.******@***.***>SubjectRe: [RozanskiT/vidmapy] how to compile kurucz stellar model (Issue #1)
I contacted you via email. Let's discuss installation issues there.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/RozanskiT/vidmapy/issues/1#issuecomment-996688170",
"url": "https://github.com/RozanskiT/vidmapy/issues/1#issuecomment-996688170",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by cxl4444** [comment]
Hello,My email address is ***@***.*** I am looking forward to your friendly reply.Best regards!---- Replied Message ----FromTomasz ***@***.***>Date12/17/2021 20:33 ***@***.***> ***@***.******@***.***>SubjectRe: [RozanskiT/vidmapy] how to compile kurucz stellar model (Issue #1)
I contacted you via email. Let's discuss installation issues there.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/RozanskiT/vidmapy/issues/1#issuecomment-996688170",
"url": "https://github.com/RozanskiT/vidmapy/issues/1#issuecomment-996688170",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
